name: Variables and secrets
on: [push]

jobs:
  decrypt-file:
    runs-on: ${{ vars.JOBS_RUNNER }}
    steps:
      - uses: actions/checkout@v3
      - name: Decrypt file
        env:
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
        run: |
          mkdir $HOME/secrets
          gpg --quiet --batch --yes --decrypt --passphrase="$PASSPHRASE" --output $HOME/secrets/scret.json secret.json.gpg
      - name: View file content (NEVER DO THIS test values anywa)
        run: cat $HOME/secrets/scret.json

  log-vars:
    runs-on: ${{ vars.JOBS_RUNNER }}
    environment: "staging"
    env:
      BOOLEAN_SECRET: ${{ secrets.BOOLEAN_SECRET }}
      ENV_LEVEL_VAR: ${{ vars.ENV_LEVEL_VAR }}
      REPO_LEVEL_VAR: ${{ vars.REPO_LEVEL_VAR }}
      ORG_LEVEL_VAR: ${{ vars.ORG_LEVEL_VAR }}
    steps:
      - name: Run only if BOOLEAN_SECRET is true
        if: env.BOOLEAN_SECRET == 'true'
        run: echo "I run"
      - name: Log Vars
        run: |
          echo '${{ vars.JOBS_RUNNER }}'
          echo "ORG_LEVEL_VAR: $ORG_LEVEL_VAR"
          echo "ENV_LEVEL_VAR: $ENV_LEVEL_VAR"
          echo "REPO_LEVEL_VAR: $REPO_LEVEL_VAR"
