name: Working Dir & Shells
on: [push]

jobs:
  display-wd-info:
    runs-on: ubuntu-latest
    steps:
      - name: Display working directory & list Files
        run: |
          pwd
          ls -a
          echo $GITHUB_SSH
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE

  display-wd-info-windows:
    runs-on: windows-latest
    steps:
      - name: Display working directory & list Files
        run: |
          pwd
          ls -a
          echo $GITHUB_SSH
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
